# Generated by Django 3.2.13 on 2022-04-20 05:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Password')),
                ('last_name', models.CharField(blank=True, db_index=True, default='', max_length=60, null=True, verbose_name='Last name')),
                ('first_name', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='First name')),
                ('google_name', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Google name')),
                ('google_id', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('google_img', models.URLField(blank=True, null=True)),
                ('phone1', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone2', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=30, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=30, null=True, verbose_name='Zipcode')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Country')),
                ('client_lat', models.FloatField(blank=True, null=True)),
                ('client_lng', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFinances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('social_security', models.CharField(blank=True, max_length=32, null=True, verbose_name='Social Security Number')),
                ('credit_score', models.IntegerField(blank=True, default=0, null=True)),
                ('available_capital', models.CharField(blank=True, choices=[('0-50,000', '0-50,000'), ('50,000-80-000', '50,000-80,000'), ('80,000-120,000', '80,000-120,000'), ('120,000-250,000', '120,000-250,000'), ('Over 250,000', 'Over 250,000')], max_length=30, null=True, verbose_name='Amount you plan to invest')),
                ('place_of_employment', models.CharField(blank=True, max_length=128, null=True, verbose_name='Place of Employment')),
                ('annual_salary', models.IntegerField(blank=True, null=True, verbose_name='Annual Salary')),
                ('years_at_job', models.IntegerField(blank=True, null=True, verbose_name='Years at Job')),
                ('other_business', models.CharField(blank=True, max_length=100, null=True)),
                ('open_in_one_to_three', models.BooleanField(blank=True, null=True)),
                ('working_capital', models.IntegerField(blank=True, null=True, verbose_name='Working Capital')),
                ('financial_strength', models.IntegerField(choices=[(1, '1 No cash, poor credit profile, no other resources..'), (2, '2 Maybe cash, no partner, limited credit call...'), (3, '3 Maybe cash, no additional resources, 100% financing...'), (4, '4 Part cash, part financing...'), (5, "5 Financing, some personal assets: i.e. 401k/IRS, current cc's, HELOC: NO CASH..."), (6, '6 Cash buyer...')], default=1, verbose_name='Financial Strength')),
                ('financing_cash', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cash Funds')),
                ('financing_loc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Line of Credit')),
                ('financing_hloc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Home Equity LOC')),
                ('financing_401k', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='401K Funds')),
                ('financing_pension', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Pension Funds')),
                ('financing_ira', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='IRA Funds')),
                ('financing_stocksbonds', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Stocks and Bonds')),
                ('financing_cd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='CD Funds')),
                ('financing_lifeinsurance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Life Insurance')),
                ('financing_credit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Credit Cards')),
                ('financing_financing_auto_loan', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Auto Loan')),
                ('financing_mortgage_primary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Mortgage Primary')),
                ('financing_mortgage_other', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Mortgage Other')),
                ('financing_installment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Installment Payments')),
                ('financing_debts_other', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Other Debts')),
                ('fi_target_date', models.DateField(blank=True, null=True, verbose_name='Finance Target Date')),
                ('fi_turnover_date', models.DateTimeField(blank=True, null=True, verbose_name='Finance Turn Over Date')),
                ('funding_path', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_preaproved', models.IntegerField(blank=True, null=True, verbose_name='Amount Pre-Approved')),
                ('amount_obtained', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_name', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Google name')),
                ('google_id', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('google_img', models.URLField(blank=True, null=True)),
                ('color_theme', models.CharField(choices=[('indigo', 'indigo'), ('blue', 'blue'), ('black', 'black'), ('dark-grey', 'dark-grey'), ('grey', 'grey'), ('brown', 'brown'), ('blue-grey', 'blue-grey'), ('deep-orange', 'deep-orange'), ('orange', 'orange'), ('amber', 'amber'), ('yellow', 'yellow'), ('khaki', 'khaki'), ('lime', 'lime'), ('light-green', 'light-green'), ('green', 'green'), ('teal', 'teal'), ('cyan', 'cyan'), ('light-blue', 'light-blue'), ('deep-purple', 'deep-purple'), ('purple', 'purple'), ('pink', 'pink'), ('red', 'red'), ('eztrak', 'eztrak')], default='indigo', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('store_state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=30, null=True, verbose_name='State')),
                ('store_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode')),
                ('store_lat', models.FloatField(blank=True, null=True)),
                ('store_lng', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcc', to='eztrak.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcp', to='eztrak.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(related_name='ldskjkds', through='eztrak.ProjectClient', to='eztrak.Client'),
        ),
        migrations.AddField(
            model_name='project',
            name='salesrep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_salesrep', to='eztrak.employee'),
        ),
        migrations.AddField(
            model_name='client',
            name='finances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance', to='eztrak.clientfinances'),
        ),
    ]
