# Generated by Django 3.2.13 on 2022-04-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eztrak', '0002_auto_20220420_0739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='StoreSite',
        ),
    ]
