# Generated by Django 3.2.13 on 2022-04-20 11:17

from django.db import migrations, models
import django.db.models.deletion
import eztrak.models


class Migration(migrations.Migration):

    dependencies = [
        ('eztrak', '0003_rename_site_storesite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesite',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eztrak.project', verbose_name='store-sites'),
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=eztrak.models.storage_path)),
                ('storesite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='eztrak.storesite')),
            ],
        ),
    ]
